### ISSUE TITLE
Upgrading of elasticsearch-mock form v1.0 to v2.0

### ISSUE THREAD

**Issue by mystical-ryan** [elastic/elasticsearch-js-mock#27]
Hi, I got a `currentNode.createStaticChild is not a function` from `find-my-way` after upgrading to v2.0. Can check if anyone face the same issue as me?

**Comment by joecullinbarracuda** [comment]
Same problem here. We're upgrading from 1 to 2 also.

Only happens for mocking paths with wildcards, like `path: "/my-index*/_search"`
